### ISSUE TITLE
Is it supposed to say 5 bytes here, or 4?

### ISSUE THREAD

**Issue by daveloyall** [syncsynchalt/illustrated-tls#1]
https://github.com/syncsynchalt/illustrated-tls/blob/ca15ef399709e85d8b39896dc352239df01e4988/site/index.html#L261

I see four bytes that follow.  Is this a bug or did I miss something?

**Comment by syncsynchalt** [comment]
Bug #3, thanks for finding it

**Comment by syncsynchalt** [comment]
Fixed in https://github.com/syncsynchalt/illustrated-tls/commit/e4b3af75e2eb452d51e483fe9d4724e3321ac815
