### ISSUE TITLE
Question about https://tls.ulfheim.net/

### ISSUE THREAD

**Issue by NN-Binary** [syncsynchalt/illustrated-tls#10]
Hi,

Thanks for this wonderful work! Made me understand so much about TLS 1.2
i'm confused about the part where you wrote CLIENT HANDSHAKE FINISHED

In the Encryption IV, The client has sent an initialization vector for decrypting this block. Because we have overridden the rand function it is a predictable sequence.
 and the Encrypted Data as well.

Where does the IV come from? Also the "data" that you encrypt, can you specify exactly which one, I find all the things so clear but this part is not for me.

16 03 03 00 40 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 22 7b c9 ba 81 ef 30 f2 a8 a7 8f f1 df 50 84 4d 58 04 b7 ee b2 e2 14 c3 2b 68 92 ac a3 db 7b 78 07 7f dd 90 06 7c 51 6b ac b3 ba 90 de df 72 0f
Decryption
14 00 00 0c cf 91 96 26 f1 36 0c 53 6a aa d7 3a

Is all this part also sent to the Server? Or just the encrypted version?

Thanks so much for the clarification :)

**Comment by syncsynchalt** [comment]
Hi!  To answer your questions:
- the IV is generated out of nothing (it is supposed to be purely random data).  The IV is needed as an input for this particular encryption algorithm, and it is a requirement of the algorithm that the data is random so the output is permuted in a way that prevents certain attacks.  (Of course in our example the randomness is removed, thus the predictable IV of [0x40, 0x41, ... 0x4f])
- The data that was encrypted is the string "14 00 00 0c cf 91 96 26 f1 36 0c 53 6a aa d7 3a" (marked in the document in green).  The first part "14 00 00 0c" is a type and length header, and the latter part "cf 91 96 26 f1 36 0c 53 6a aa d7 3a" is the encrypted payload that is sent.  This payload is a hash of the handshake conversation that was calculated by the client.
- Only the encrypted version is sent to the server.  The server must decrypt the data using the keys that have been calculated in the handshake, and then it must look at the decrypted data and compare that to a hash of the handshake conversation that it calculated itself (in the same way that the client had calculated it).  If this data matches then it knows that both the client and server calculated the same encryption keys, and that they also agree on what data had been sent in the handshake conversation (no tampering took place).  If this doesn't match the connection is aborted.

I hope this helps!

**Comment by NN-Binary** [comment]
Awesome thanks for the detail. I know have a way clearer vision of this part
To clarify, the IV is sent to the server too right?

**Comment by syncsynchalt** [comment]
@HandleMaser Yes, an IV is sent in the clear.  The only security requirement is that the client does not re-use it (this is ensured by randomness and length, it's not actually checked).

**Comment by NN-Binary** [comment]
Thanks for the clarifications and your time!
Have a great day ahead
