### ISSUE TITLE
why sha256 = 256 bytes?

### ISSUE THREAD

**Issue by lomateron** [syncsynchalt/illustrated-tls#11]
in https://tls.ulfheim.net
then Server key exchange
then Signature
it says
the computed signature for...
SHA256(client_hello_random + server_hello_random + curve_info + public_key)
wikipedia says that the output of SHA256 is 32bytes
so is your page wrong or
where did you get those 256 byes from

**Comment by syncsynchalt** [comment]
As you say, SHA256 only outputs 256 bits (32 bytes).  But the data represented in the "Signature" section is not actually a SHA256 hash, it is the RSA *signature* of a SHA256 hash.

An RSA signature is defined to be the same size as the key modulus, which for this connection is 2048 bits (or 256 bytes):
```
$ openssl pkey -in server.key  -noout -text
Private-Key: (2048 bit)
```

So what about the SHA256 hash?  What is happening is that both the client and the server have all the information necessary to independently create the same hash data.  The server then signs that 32 bytes of hash data with the private key, and the client verifies that signature with the public key.  This allows both sides to know that none of the data that went into the hash was tampered with, and that the key exchange was successful.

**Comment by lomateron** [comment]
wouldn't it be better to replace
SHA256(client_hello_random + server_hello_random + curve_info + public_key)
with
RSASSA-PSS-SIGN(client_hello_random + server_hello_random + curve_info + public_key)
and say that RSASSA-PSS-SIGN internally will use the
server's certificate private key and sha256
and maybe point to
https://tools.ietf.org/html/rfc3447#section-8.1.1
or
https://tools.ietf.org/html/rfc8017#section-8.1.1
also
am not really sure if I am right
