### ISSUE TITLE
Question about a source of a claim

### ISSUE THREAD

**Issue by borrrden** [syncsynchalt/illustrated-tls#17]
https://github.com/syncsynchalt/illustrated-tls/blob/fe8fbe46731428106fac948ebef33fe4062f28a8/site/index.html#L112-L116

This section states that the practice of using unix time in the hello random bytes is recommended against, but the link is an expired draft of a document.  Is there any non-expired official document that backs up this recommendation because I see many libraries using the unix time anyway.  This includes mbedTLS, Apple's NSURL framework, and OkHttp for Java.

**Comment by syncsynchalt** [comment]
Hi Jim!  I do not have an updated reference off-hand, but I think the reasoning in this draft still stands (even though the draft is expired).  It's not unusual for an IETF draft to expire but to still stand as the most authoritative reasoning for a best practice, and that might be the situation that we have here.

It looks like both the author and the draft itself are in github at https://github.com/nmathewson/draft-nogmtut, you might want to check in with Nick and see if his draft got absorbed anywhere or if anything interesting came up with with regards to it.  If you do find out anything interesting let me know and I may include it here.

Closing the issue out for now, I think I've answered as best I can.
