### ISSUE TITLE
Wrong verify_data?

### ISSUE THREAD

**Issue by Biganon** [syncsynchalt/illustrated-tls#18]
Not entirely sure, but I think there might be a mismatch between the verify_data in these two places (both in Client Handshake Finished > Verify Data):

- "The verify data calculated from this hash is **a0744dd49a212f152b3c060d**"

- "hexdump /tmp/verify_data: 0000000 **cf 91 96 26 f1 36 0c 53 6a aa d7 3a**"

**Comment by syncsynchalt** [comment]
Thanks Simon, good spotting!  This must have been a hardcoded value left over from an earlier capture.  Fixed in 06c1c8d7de0c6d5780325a68b7b675c18ec3716e .

**Comment by Biganon** [comment]
I just noticed the same problem appears in Server Handshake Finished, didn't spot it the first time!

**Comment by syncsynchalt** [comment]
Aha, taking a look there too.  Hopefully the same issue...

**Comment by syncsynchalt** [comment]
544ee6af859e4881a9cb59585fe207fc1df0b5a3 Yep, the same issue.  Thanks again!
