### ISSUE TITLE
Make each step "linkable"

### ISSUE THREAD

**Issue by farnulfo** [syncsynchalt/illustrated-tls#20]
Hi,

It will be cool to have :
https://tls12.xargs.org#ServerKeyExchange => open the page with Server Key Exchange section expanded

**Comment by syncsynchalt** [comment]
Hi Franck, I think that's a great idea. I'll see what I can put together next week.

(Sorry for the late reply, been on a motorcycle trip)

**Comment by syncsynchalt** [comment]
Let me know what you think of the implementation, which modifies the URL in-place for what you're viewing.  I have it currently set to replace the URL on each section change and not leave the old URL in browser history, but that's an easy change to make that I'm considering.

**Comment by farnulfo** [comment]
It looks great !
Thanks
