### ISSUE TITLE
[ASK] what is the client handshake finished message mean?

### ISSUE THREAD

**Issue by KevinAdhaikal** [syncsynchalt/illustrated-tls#25]
Hello, i want to ask about this

```
0000000 14 00 00 0c cf 91 96 26 f1 36 0c 53 6a aa d7 3a
0000010 a5 a0 3d 23 30 56 e4 ac 6e ba 7f d9 e5 31 7f ac
0000020 2d b5 b7 0e 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b
```

at `0000000` contain handshake header and verify data.
but, what is at `0000010` and `0000020` data mean? is it just random data?

if its just random data. what happens if i delete the random data? is it still work?

sorry if my grammar is bad.

**Comment by syncsynchalt** [comment]
Hi Kevin,

That is part of the output of the `hexdump` command, which prints the current byte offset as it goes.  For example:
```
$ echo "foo bar baz bux barney" | hexdump -C
00000000  66 6f 6f 20 62 61 72 20  62 61 7a 20 62 75 78 20  |foo bar baz bux |
00000010  62 61 72 6e 65 79 0a                              |barney.|
00000017
```
if we were puzzling over some binary data (which is what hexdump is for), we can see the first letter of `barney` is at offset 0x00000010 in the input.

You can safely ignore the offset column in the examples shown in the page.

I'd prefer to not have the offsets printed at all (they're not useful for what I'm trying to show), but unfortunately the standard binary-to-hex commands (`od` and `hexdump`) make it difficult to suppress, and the third binary-to-hex command (`xxd`) doesn't print data in exactly the format I want.

To suppress the offset column in `hexdump`, the command would be `hexdump -e '16/1 "%02x " "\n"'`, which I think would just confuse readers in a different way.  In the end, I chose the command `hexdump` with no arguments (or with argument `-C` when needed) since the simple command name tells users what is intended.

**Comment by KevinAdhaikal** [comment]
Oh okay, but, I mean this data after the handshake header and verify data (after 16 bytes)
```
a5 a0 3d 23 30 56 e4 ac 6e ba 7f d9 e5 31 7f ac
2d b5 b7 0e 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b
```
This is just a random Data or what?

**Comment by syncsynchalt** [comment]
Ah, I see, I misunderstood.

Much of that is a 160-bit MAC ([message authentication code](https://en.wikipedia.org/wiki/Message_authentication_code)):
```
The last 32 bytes contain a 20-byte MAC and padding to bring the data to a
multiple of 16 bytes.  The 20-byte MAC can be reproduced as follows:

### from https://tools.ietf.org/html/rfc2246#section-6.2.3.1
$ sequence='0000000000000000'
$ rechdr='16 03 03'
$ datalen='00 10'
$ data='14 00 00 0c cf 91 96 26 f1 36 0c 53 6a aa d7 3a'
### from "Encryption Keys Calculation"
$ mackey=1b7d117c7d5f690bc263cae8ef60af0f1878acc2
$ echo $sequence $rechdr $datalen $data | xxd -r -p \
  | openssl dgst -sha1 -mac HMAC -macopt hexkey:$mackey

a5a03d233056e4ac6eba7fd9e5317fac2db5b70e
```

I think in this version of TLS it has two purposes, one to add additional protection and integrity, and two to verify that the decryption was successful (so that garbage data isn't sent to the application). In later versions of TLS (1.3) the cipher mechanisms are required to support AEAD instead, so that MACs like these aren't present in the decrypted data and are instead folded into the encrypt/decrypt mechanism.

The string `0b 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b` is padding, the mechanism used in TLS is to pad with a byte value that is the number of pad bytes (`0xb` = 11 bytes of padding will follow, and then 11 `0xb` bytes).  It doesn't look like I explained the padding mechanism in this page, here's a quote from the TLS 1.2 RFC:

```
   padding
      Padding that is added to force the length of the plaintext to be
      an integral multiple of the block cipher's block length.  The
      padding MAY be any length up to 255 bytes, as long as it results
      in the TLSCiphertext.length being an integral multiple of the
      block length.  Lengths longer than necessary might be desirable to
      frustrate attacks on a protocol that are based on analysis of the
      lengths of exchanged messages.  Each uint8 in the padding data
      vector MUST be filled with the padding length value.  The receiver
      MUST check this padding and MUST use the bad_record_mac alert to
      indicate padding errors.
```

**Comment by KevinAdhaikal** [comment]
So, 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b just to make it fit to 48 bytes, right?

**Comment by syncsynchalt** [comment]
Yes, that's right (well, a multiple of 256 bits, or 32 bytes, actually).

I think this is because the symmetric cipher requires input/output in full blocks, and in this case it's a 256-bit cipher.

**Comment by KevinAdhaikal** [comment]
And btw, I want to ask again

Is TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f) and TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013) is different? I mean the structure packet

**Comment by KevinAdhaikal** [comment]
Or the all cipher in TLS 1.2 are same the packet structure? But it's just different in hash and encrypt?

**Comment by syncsynchalt** [comment]
Ahh, "cipher suites" have gotten very complicated 😆 

Those both use ECDHE for key exchange, and they both perform AES-128 symmetric encryption. They use different hash algorithms (SHA-2 256 vs SHA-1, which is insecure). The CBC and GCM encryption modes are very different (CBC will need a MAC, but GCM is an AEAD mode that encompasses its own MAC mechanism, and is overall more secure and tamper-proof).

Of those two, `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` is more secure, and more closely matches what is used in TLS 1.3.

**Comment by syncsynchalt** [comment]
I should also have mentioned, when it comes to `AES-128-CBC` vs `AES-128-GCM` I just leave the details to an encryption lib/tool like openssl.  It's good to know they are different and which is better, but I no longer memorize the exact details of how the input/output is constructed :smile:

**Comment by KevinAdhaikal** [comment]
Oh, so... At client handshake finished, CBC and GCM data structure are different? Right?

**Comment by KevinAdhaikal** [comment]
Btw, I'm sorry if my grammar is bad, and i'm sorry if I bother your time. Hehe...

**Comment by syncsynchalt** [comment]
In terms of the connection, everything is almost the same except the settings passed to the encrypt/decrypt function. You may also see longer hashes in various places in the SHA256 method, and the CBC method will also include those MACs (which are missing in the GCM method, since they're removed by the GCM process)

**Comment by syncsynchalt** [comment]
Your grammar is fine 😆

**Comment by syncsynchalt** [comment]
> Oh, so... At client handshake finished, CBC and GCM data structure are different? Right?

I think the MAC data will likely be missing in the GCM version.  The MAC data is _there_, it's just added/removed as part of the encrypt/decrypt function for a GCM cipher, and so it doesn't appear in the output when using a tool like `openssl`.

**Comment by KevinAdhaikal** [comment]
> > Oh, so... At client handshake finished, CBC and GCM data structure are different? Right?
> 
> I think the MAC will likely be missing in the GCM version

I don't need add MAC on Client finished handshake, am I right?

**Comment by KevinAdhaikal** [comment]
Hmmmmmm... Im still confused, hehe...

**Comment by KevinAdhaikal** [comment]
Is AES_128_GCM Need to add this? Like AES_128_CBC
```
a5 a0 3d 23 30 56 e4 ac 6e ba 7f d9 e5 31 7f ac
2d b5 b7 0e 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b 0b
```

**Comment by syncsynchalt** [comment]
> I don't need add MAC on Client finished handshake, am I right?

I think if you're using CBC cipher you need to add the MAC when encrypting / verify/remove it when decrypting.

I think if you're using GCM cipher you don't need to worry about it, it's automatically added/removed by the GCM cipher function.

TLS 1.2 got very confusing at the end of its life, TLS 1.3 simplifies all this (the only allowed cipher options are AEAD ciphers like GCM, so there is no weird MAC to add or worry about)

**Comment by syncsynchalt** [comment]
> Is AES_128_GCM Need to add this? Like AES_128_CBC

No, in GCM mode it's automatically included/created/hidden as part of the GCM process.  GCM (like all AEAD processes) automatically includes a MAC without the caller being able to use it wrong, leave it out, etc.

(There are security implications, for example some implementations might forget to verify the mac, or they might verify the mac in a way that exposes timing information, so newer implementations lock everything inside the process and make sure it's done securely.  This might not make sense, don't worry about it)

**Comment by KevinAdhaikal** [comment]
ohh... because, i try to make TLS Client using C programming, and I'm stuck at "Client Handshake Finished"

**Comment by KevinAdhaikal** [comment]
and i am always failed at "Client Handshake Finished" hehe...

**Comment by KevinAdhaikal** [comment]
![image](https://github.com/user-attachments/assets/64c9a619-d912-4978-a425-894550b63fae)
i always get this after sending the "Client Handshake Finished" to the server (btw i am using Node JS Server for the example)

**Comment by KevinAdhaikal** [comment]
and what is the data mean btw?

**Comment by KevinAdhaikal** [comment]
btw, i want to ask Encryption IV at Client Handshake Finished too

Is it made random and send it to Server, or is it used from the client write IV, and then send it to Server?

**Comment by syncsynchalt** [comment]
> ohh... because, i try to make TLS Client using C programming, and I'm stuck at "Client Handshake Finished"

Yeah, that makes sense, it is the first encrypted record in the connection, so things will fail there 😄 

Without being there in person all I can do is wish you luck as you figure things out.

> btw, i want to ask Encryption IV at Client Handshake Finished too

> Is it made random and send it to Server, or is it used from the client write IV, and then send it to Server?

It is a random input created by the client, used in the encryption process, and sent in the clear to the server. [initialization vector](https://en.wikipedia.org/wiki/Initialization_vector)

If you are doing GCM I think this disappears, as GCM uses an IV derived from the record number (starting at 0x1, and incrementing by 1 for each record?  it's been a while...)

But anyway, the use of the IV is tied to the cipher selected.

**Comment by KevinAdhaikal** [comment]
> If you are doing GCM I think this disappears, as GCM uses an IV derived from the record number (starting at 0x1, and incrementing by 1 for each record? it's been a while...)

so, i dont need to add Encryption IV to the Client Handshake Finished when i am using GCM?

**Comment by KevinAdhaikal** [comment]
oh my god, my head is hurt right now, haha 😂

**Comment by syncsynchalt** [comment]
> so, i dont need to add Encryption IV to the Client Handshake Finished when i am using GCM?

I am not actually sure, in the context of TLS 1.2 (rather than TLS 1.3, which I'm more familiar with).  I don't _think_ it's needed, no.  I would use wireshark to look at a successful TLS 1.2 connection using GCM to confirm exactly what the record fields are.

**Comment by KevinAdhaikal** [comment]
oh, okay okay

**Comment by KevinAdhaikal** [comment]
maybe, i need to set my Node JS HTTPS Server to AES 128 CBC, so it's the same as on your website 😂

**Comment by KevinAdhaikal** [comment]
btw, thanks for the information bro, im sorry if i disturb you time so much

**Comment by KevinAdhaikal** [comment]
maybe, if i confused again, maybe i will go here and ask to you again, is it okay? hehe

**Comment by syncsynchalt** [comment]
No worries, I'll help where I can but some days I have more time than others 😆

**Comment by KevinAdhaikal** [comment]
oh okay okay... im sorry if i disturb your time 🙏

**Comment by KevinAdhaikal** [comment]
hello, i want to ask about sequence on handshake finished message
is it byte or just normal number?

**Comment by KevinAdhaikal** [comment]
hmmmm... i dont know why i always got alert bad_record_mac message
even though I have followed the structure on the website, but its still bad_record_mac
