### ISSUE TITLE
Support for TLS v1.3

### ISSUE THREAD

**Issue by MichalStaruch** [syncsynchalt/illustrated-tls#3]
TLS v1.3 is already there ([RFC 8446](https://tools.ietf.org/html/rfc8446)) - adding Illustrated TLS for the new version of the protocol might be useful for spreading the knowledge :).

**Comment by fproulx-dfuse** [comment]
would be awesome to show 1.3 side by side to 1.2 =)

**Comment by syncsynchalt** [comment]
I'm learning TLS 1.3 first (https://github.com/syncsynchalt/tincan-tls), will probably create the TLS 1.3 version of the document after that's done.  Thanks!

**Comment by syncsynchalt** [comment]
https://tls13.ulfheim.net
