### ISSUE TITLE
Server encryption keys calculation typos

### ISSUE THREAD

**Issue by kapad** [syncsynchalt/illustrated-tls#5]
![image](https://user-images.githubusercontent.com/2017355/47075855-07b43280-d21b-11e8-961f-ab981b44b0b0.png)

Since this is the server calculation, "client" should be replaced with "server" even though all the calculations are the same.

**Comment by syncsynchalt** [comment]
Thanks!  I was only able to spot the one error (fixed in cf6f81482c6d9edde4ca7fa83fd1a95de432378f), if there are others I missed in this area please let me know!
